apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-management
  template:
    metadata:
      labels:
        app: library-management
    spec:
      containers:
        - name: library-management
          image: amritls/library-management
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: my-registry-secret