apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  labels:
    app: book-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: amritls/book-service-2.0.0
          ports:
            - containerPort: 8081
      imagePullSecrets:
        - name: my-registry-secret
